name: Sonar Scanner
description: Perform a Sonar analysis on a project
inputs:
  sonar-host:
    description: The Sonar server URL
    required: true
  main-branch:
    description: The Sonar main branch
    required: true
    default: master
  gradle-args:
    description: Custom gradle scan command
    required: false
  maven-args:
    description: Custom maven scan command
    required: false
  msbuild:
    description: |
      Flag to indicate that the MSBuild Sonar Scanner should be used. Set to `true` to use MSBuild.
      The action will automatically track the state to know if a scan should be started or finalized.
    required: false
runs:
  using: node12
  main: dist/index.js
