name: Sonar Scanner
description: Perform a Sonar analysis on a project
inputs:
  sonar-host:
    description: The Sonar server URL
    required: true
  sonar-scanner:
    description: |
      The sonar scanner to use. Valid values are 'auto', 'maven', 'gradle', 'node' and 'dotnet'.
      The default value 'auto' will attempt to perform auto-discovery. Auto-discovery does not work for 'dotnet'.
    required: true
    default: auto
  main-branch:
    description: The Sonar main branch
    required: true
    default: master
  gradle-args:
    description: Custom gradle scan command
    required: false
  maven-args:
    description: Custom maven scan command
    required: false
  github-token-secret-name:
    description: |
      The secret name from which to load the github-token. This is only used
      when github-token has not be set explicitly.
    required: true
    default: github-token
  sonar-token-secret-name:
    description: |
      The secret name from which to load the sonar-token. This is only used
      when the sonar-token has not been set explicitly. The default value
      depends on the sonar-host and is 'sonarcloud-token' for sonarcloud and
      'sonarqube-token' otherwise.
    required: false
  service-account-key:
    description: |
      The service account key which will be used for authentication with Secret Manager.
      The account key should be a base64 encoded JSON key stored as a secret.
    required: false
  verbose:
    description: Enable verbose logging in the sonar scanner.
    required: false
    default: 'false'
runs:
  using: node12
  main: dist/index.js
