name: RS Permission Converter
description: Wraps command line tool for converting permissions for RS
inputs:
  type:
    description: sql or resx. This specifies if it is sql file or resource file to be generated.
    required: true
    default: null
  tool-version:
    description: Version of the permission converter tool
    required: false
    default: '1.0.0'
  work-directory:
    description: working directory
    required: true
    default: null
  permission-file:
    description: The path to the permsission xml file
    required: true
    default: null
  output-dir:
    description: The relative path where the resx files are generated.
    required: false
    default: null
  sql-file:
    description: The relative path and file name to the output sql file
    required: false
    default: null
runs:
  using: node18
  main: dist/index.js
