name: Vale linting
description: Vale is a command-line tool that brings code-like linting to prose.
inputs:
  exclude:
    description: A file or files that should be excluded from linting.
    required: false

runs:
  using: composite
  steps:
    - name: Lint natural language with Vale
      # Change to the latest version/tag
      uses: l0kal/vale-action@master
      with:
        styles: |
          https://github.com/extenda/docker-vale/releases/download/latest/Extenda.zip
        files: __onlyModified
        config: https://raw.githubusercontent.com/extenda/docker-vale/master/vale.ini
        exclude: ${{ inputs.exclude }}
        debug: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
