name: Cloud Run v2
description: Deploy to gke autopilot
author: Extenda Retail
inputs:
  service-account-key:
    description: |
      The service account key which will be used for authentication.
      The account key should be a base64 encoded JSON key stored as a secret.
    required: true
  service-definition:
    description: |
      The service YAML specification.
    required: false
    default: cloud-run.yaml
  image:
    description: The Docker image to deploy to Cloud Run.
    required: true
  verbose:
    description: |
      Flag to enable verbose debug logging on gcloud.
    required: false
    default: 'false'
runs:
  using: node16
  main: dist/index.js
