sonar.sourceEncoding=UTF-8
sonar.projectKey=extenda_actions
sonar.projectName=actions
sonar.sources=*/src
sonar.exclusions=**/__mocks__/**,*/dist/**
sonar.tests=*/test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=test-results/sonar-report.xml
sonar.cpd.exclusions=cloud-run/**/*,iam/**/*
