name: Maven
description: Build with Maven configured for Extenda Retail
inputs:
  args:
    description: The Maven command to run
    required: true
  version:
    description: The project version to build. This is set in the POMs before building.
    required: false
runs:
  using: node12
  main: dist/index.js
