name: Maven
description: Build with Maven configured for Extenda Retail
inputs:
  args:
    description: The Maven command to run
    required: true
  version:
    description: The project version to build. This is set in the POMs before building
    required: false
  cache-key:
    deprecationMessage: |
      Caching is no longer supported. Use the maven cache feature in `actions/setup-java@v2`.
    description: |
      The cache key to use. Set to an empty value to disable the automatically configured cache.
    default: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    required: false
  cache-restore-keys:
    deprecationMessage: |
      Caching is no longer supported. Use the maven cache feature in `actions/setup-java@v2`.
    description: |
      The cache restore keys. This value only needs to be modified if the cache key prefixes has
      been changed. Multiple keys can be specified using spaces or line breaks as separator.
    default: ${{ runner.os }}-maven-
    required: false
  service-account-key:
    description: |
      The service account key which will be used for authentication.
      The account key should be a base64 encoded JSON key stored as a secret.
    required: false
  nexus-username-secret-name:
    description: |
      The secret name in GCP secret manager that contains a Nexus user name.
      This value will not be used if `NEXUS_USERNAME` is already set as an env var.
    default: nexus-username
    required: false
  nexus-password-secret-name:
    description: |
      The secret name in GCP secret manager that contains a Nexus user password.
      This value will not be used if `NEXUS_PASSWORD` is already set as an env var.
    default: nexus-password
    required: false
  working-directory:
    description: Working dir to run action from
    required: false
runs:
  using: node20
  main: dist/index.js
