name: dora-metrics
description: Log deployment and bugs for DORA
author: Extenda Retail
inputs:
  product-component:
    description: |
      The product component for you service. (example mcpe-selfscan)
    required: true
  product-name:
    description: |
      The product name for you service. (example scan & go, iam)
    required: true
  jira-username:
    description: |
      The jira username
    required: true
  jira-password:
    description: |
      The jira password
    required: true
  jira-project-key:
    description: |
      The jira project key
    required: true
runs:
  using: node16
  main: dist/index.js
