name: Slack GitHub Bot Message
description: Send a message to Slack through the GitHub Slack Integration
inputs:
  service-account-key:
    description: |
      The service account key which will be used for authentication.
      The account key should be a base64 encoded JSON key stored as a secret.
    required: true
  text:
    description: A markdown formatted message
    required: true
  channel:
    description: |
      The channel name to notify on. ( default is your clan alert channel )
    required: false
runs:
  using: node12
  main: dist/index.js
