name: 'Setup MSBuild.exe'
description: 'Uses VSWhere.exe to locate latest MSBuild & put it into the PATH'
author: 'Warren Buckley'
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'download'
  color: 'purple'
