# action.yml
name: 'k6'
description: 'Trigger k6 acceptance test'
inputs:
  flags:
    description: 'Additional flags to be passed on to k6'
    required: false
    default: ''
  version:
    description: 'k6 version to use'
    required: false
    default: ''
  parallel:
    description: Run tests in parallel
    required: false
    default: 'false'
  scripts:
    description: 'Path to test script(s)'
    required: false
    default: './acceptance/k6/*.js'
  only-verify-scripts:
    description: 'Verify if scripts are valid'
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - uses: grafana/setup-k6-action@v1
      with:
        k6-version: ${{ inputs.version }}
    - uses: grafana/run-k6-action@v1
      with:
        path: ${{ inputs.scripts }}
        cloud-run-locally: false
        parallel: ${{ inputs.parallel }}
        flags: ${{ inputs.flags }}
        only-verify-scripts: ${{ inputs.only-verify-scripts }}
