name: Styra DAS test
description: |
  Execute unit tests for Rego rules inside Styra DAS.
  The following files are expected to exist in your project:
    - policies/policy/com.styra.envoy.ingress/test/test/test.rego
    - policies/policy/com.styra.envoy.ingress/rules/rules/ingress.rego
inputs:
  styra-das-token:
    description: The token used to make api calls to Styra DAS
    required: true
  permission-prefix:
    description: |
      The permission-prefix setup for the service in you clan-common-repo
    required: true
  service-name:
    description: |
      The name of the service
    required: true
  styra-url:
    description: |
      The styra DAS url
    default: https://extendaretail.svc.styra.com
    required: false
  policy-type:
    description: |
      The policy you are testing, ingress or app ( default: ingress )
    default: ingress
    required: false
runs:
  using: composite
  steps:
    - uses: extenda/actions/opa-policy-test@v0
      with:
        service-account-key: inherit
        permission-prefix: ${{ inputs.permission-prefix }}
        service-name: ${{ inputs.service-name }}
