name: publish openapi
description: Using an open api yaml file to generate static html page to display api documentation
inputs:
  openapi:
    description: The path towards your openapi yaml file
    required: true
  api-name:
    description: Your api service name
    required: true
  release-tag:
    description: Your api version documentation
    required: true
  system-name:
    description: The system your api belongs to
    required: true
  bucket:
    description: The bucket to upload the generated files to
    required: false
runs:
  using: node16
  main: dist/index.js
