name: styra-das-deploy
description: publish staging policy into production DAS system
author: Extenda Retail
inputs:
  styra-das-token:
    description: |
      The token used to make api calls to Styra
    required: true
  permission-prefix:
    description: |
      The permission-prefix setup for the service in you clan-common-repo
    required: true
  service-name:
    description: |
      The name of the service
    required: true
  styra-url:
    description: |
      The styra DAS url
    default: https://extendaretail.svc.styra.com
    required: false
runs:
  using: node12
  main: dist/index.js
