name: Customer Configuration
description: Set up configuration definitions and defaults in CCC
author: Extenda Retail
inputs:
  service-account-key:
    description: |
      The service account key which will be used for authentication
      to the secrets manager.
    required: true
  definitions:
    description: |
      Customer controlled configuration definition.
    required: false
    default: customer-config/*.yaml
  dry-run:
    description: |
      If 'true', action will be done.
    required: false
    default: 'false'
runs:
  using: node20
  main: dist/index.js
