name: Quality Gate
description: Enforce a quality gate on your software project.
inputs:
  github-token:
    description: The GitHub Actions token.
    default: ${{ github.token }}
  quality-gate-token:
    description: |
      The access token of the quality gate service provider.
    required: true
  code-owners:
    description: |
      The team name of the code owners. This can be used to organize projects
      within the quality gate reporting dashboards.
    required: true
runs:
  using: composite
  steps:
    - name: Setup Qodana
      uses: extenda/actions/setup-qodana@feat/quality-gate
      id: setup-qodana
      with:
        qodana-token: ${{ inputs.quality-gate-token }}
        qodana-team: ${{ inputs.code-owners }}
        github-token: ${{ inputs.github-token }}

    - name: List contents before
      if: always()
      run: |
        pwd
        ls -al
      shell: bash

    - name: Scan with Qodana
      uses: extenda/qodana-action@feat/issue-number-discovery
      with:
        args: ${{ steps.setup-qodana.outputs.args }}
        github-token: ${{ inputs.github-token }}
      env:
        QODANA_TOKEN: ${{ steps.setup-qodana.outputs.project-token }}

    - name: List contents after
      if: always()
      run: |
        pwd
        ls -al
      shell: bash
