name: Quality Gate
description: Enforce a quality gate on your software project.
inputs:
  secrets-account-key:
    description: |
      The service account key which will be used to access CI/CD pipeline secrets.
      This must be set unless the `QUALITY_GATE_TOKEN` environment variable is set
      with the access token for the service provider.
  github-token:
    description: The GitHub Actions token.
    default: ${{ github.token }}
  collection:
    description: |
      The collection name under which the project will be sorted. This can be a
      team name or a category. This can be used to organize projects within
      the quality gate reporting dashboards.
    required: true
runs:
  using: composite
  steps:
    - name: Resolve quality gate access token
      if: env.QUALITY_GATE_TOKEN == ''
      uses: extenda/actions/gcp-secret-manager@v0
      with:
        service-account-key: ${{ inputs.secrets-account-key }}
        secrets: |
          QUALITY_GATE_TOKEN: qodana-organization-token

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45

    - name: Setup Qodana
      uses: extenda/actions/setup-qodana@feat/quality-gate
      id: setup-qodana
      with:
        qodana-token: ${{ env.QUALITY_GATE_TOKEN }}
        qodana-team: ${{ inputs.collection }}
        github-token: ${{ inputs.github-token }}

    - name: Scan with Qodana
      uses: extenda/qodana-action@feat/issue-number-discovery
      with:
        args: ${{ steps.setup-qodana.outputs.args }}
        github-token: ${{ inputs.github-token }}
        # If qodana.yaml is added in this branch we do not enter PR mode.
        pr-mode: ${{ contains(steps.changed-files.outputs.added-files, 'qodana.yaml') == false }}
      env:
        QODANA_TOKEN: ${{ steps.setup-qodana.outputs.project-token }}
