name: Cloud Run v2
description: Deploy to Cloud Run and gke autopilot
author: Extenda Retail
inputs:
  service-account-key-pipeline-secrets:
    description: |
      The service account key which will be used for authentication aginst the pipeline secrets project.
      Necessary if OPA is enabled.
    required: false
  service-account-key:
    description: |
      The service account key which will be used for authentication against the clan project.
    required: true
  service-definition:
    description: |
      The service YAML specification.
    required: false
    default: cloud-run.yaml
  image:
    description: The Docker image to deploy to Cloud Run.
    required: true
  migrate:
    description: Migrate the dns mappings to the new loadbalancer
    required: false
    default: 'false'
runs:
  using: node16
  main: dist/index.js
