name: IAM test token
description: Obtain a valid ID token from the Hii Retail IAM
author: Extenda Retail
inputs:
  service-account-key:
    description: |
      The service account key which will be used for authentication
      to the secrets manager.
    required: true
  user-email:
    description: |
      Test user email (can be secret or full email).
    default: iam-test-token-email
    required: false
  user-password:
    description: |
      Test user password secret name.
    default: iam-test-token-password
    required: false
  api-key:
    description: |
      Api key for identity platform.
    required: true
  tenant-id:
    description: |
      Tenant id for tests to run against.
    default: testrunner-2mfuk
    required: false
outputs:
  iam-token:
    description: The test user's ID token.
runs:
  using: node20
  main: dist/index.js
