name: Business unit group type
description: Publish group types to business unit manager service
author: Extenda Retail
inputs:
  service-account-key:
    description: |
      The service account key which will be used for authentication
      to the secrets manager.
    required: true
  service-account-key-staging:
    description: |
      The service account key used to authenticate to your stagin project
    required: true
  service-account-key-prod:
    description: |
      The service account key used to authenticate to your prod project
    required: true
  bum-definition:
    description: |
      The business unit group type YAML specification.
    required: true
    default: bum/*.yaml
  bum-api-url:
    description: |
      The Hii Retail Business Unit Manager API URL.
    required: true
    default: https://business-unit-api.retailsvc.com
  dry-run:
    description: |
      If 'true' stop after validating the YAML schema. No remote systems will be updated.
    required: false
    default: 'false'
runs:
  using: node12
  main: dist/index.js
