name: Cloud Run
description: Deploy to Cloud Run
author: Extenda Retail
inputs:
  service-account-key:
    description: |
      The service account key which will be used for authentication.
      The account key should be a base64 encoded JSON key stored as a secret.
    required: true
  service-definition:
    description: |
      The service YAML specification.
    default: cloud-run.yaml
  image:
    description: The Docker image to deploy to Cloud Run.
    required: true
  runtime-account-email:
    description: |
      The runtime service account used by the Cloud Run service. This can either be specified as a fully-qualified
      email address, for example `my-service@my-gcp-project.iam.googleservices.com` or as the prefix `my-service`.
      When a prefix is used, the action will automatically append the email domain based on the current GCP project.
    default: cloudrun-runtime
runs:
  using: node12
  main: dist/index.js
