name: Cloud Run
description: Deploy to Cloud Run
author: Extenda Retail
inputs:
  service-account-key:
    description: |
      The service account key which will be used for authentication.
      The account key should be a base64 encoded JSON key stored as a secret.
    required: true
  service-definition:
    description: |
      The service YAML specification.
    default: cloud-run.yaml
  image:
    description: The Docker image to deploy to Cloud Run.
    required: true
runs:
  using: node12
  main: dist/index.js
