name: Conventional release
description: |
  Create a release based based on conventional commit conventions.

  This action will create a tag and a corresponding release on GitHub.
  Use the outputs of this step to build your software in the workflow.
inputs:
  tag-prefix:
    description: The release tag prefix
    required: true
    default: v
  name:
    description: The product name to include in the release title. This should not contain a version.
    required: false
    default: Release
  pre-release:
    description: Mark as pre-release
    required: false
    default: false
  make-latest:
    description: Mark as latest release
    required: false
    default: true
outputs:
  release-tag:
    description: The created release tag
  version:
    description: The tagged version
  release-changelog:
    description: The latest release change log
  release-id:
    description: The ID of the created GitHub release
runs:
  using: node20
  main: dist/index.cjs
