name: Run Trivy vulnerability scanner
description: Run Trivy vulnerability scanner and generate a report and save it to a Slack channel
author: Extenda
inputs:
  image-ref:
    description: The reference to the image to scan
    required: true
  application-name:
    description: The name of the application
    required: false
    default: ''
    deprecationMessage: Not in use.
  service-account-key:
    description: The service account key to use for authentication for the Slack API
    required: true
  channel:
    description: The Slack channel to send the notification to
    required: false
    default: ''
    deprecationMessage: Not in use. The default alert channel for the clan will be used.
  level:
    description: The level of vulnerability to check for (CRITICAL, HIGH, MEDIUM, LOW) ex. CRITICAL\|HIGH
    required: false
    default: CRITICAL\|HIGH
    deprecationMessage: Not in use.
runs:
  using: composite
  steps:
    - name: Run Trivy scanner
      uses: extenda/actions/trivy-scan@v0
      with:
        image: '${{ inputs.image-ref }}'
        service-account-key: ${{ inputs.service-account-key }}
