name: IAM permissions
description: Publish permissions to Hii Retail IAM
author: Extenda Retail
inputs:
  service-account-key:
    description: |
      The service account key which will be used for authentication
      to the secrets manager.
    required: true
  service-account-key-staging:
    description: |
      The service account key used to authenticate to your stagin project
    required: true
  service-account-key-prod:
    description: |
      The service account key used to authenticate to your prod project
    required: true
  iam-definition:
    description: |
      The IAM YAML specification.
    required: false
    default: iam.yaml
  styra-url:
    description: |
      The styra url
    required: false
    default: https://extendaretail.styra.com
runs:
  using: node12
  main: dist/index.js
