name: Terraform plan comment
description: Post a Terraform plan output as a pull request comment.
inputs:
  plan-file:
    description: |
      The plan output filename. The action will include all plans matching this name below the working directory.
    required: false
    default: plan.out
  github-token:
    description: A GitHub token with write access to the repository.
    required: false
    default: ${{ github.token }}
  repository:
    description: |
      The repository to post to. When set to another repository than the one running the workflow,
      also set the `pull-request-number`.
    required: false
    default: ${{ github.repository }}
  pull-request-number:
    description: |
      The pull request number to post to. If not specified, this will be determined
      from the github context.
    required: false
  working-directory:
    description: The working directory. Defaults to the current working directory.
    required: false
  footer:
    description: Custom footer message to add after plan outputs. Can contain Markdown.
    required: false
  max-terraform-processes:
    description: Maximum number of terraform processes running at the same time
    required: false
    default: 10
  ignored-resources-regexp:
    description: Pattern of resource names for ignore in pull request comment if only those resources are planned to change.
    required: false
runs:
  using: node18
  main: dist/index.js
