name: Create RS Installer Package
description: Creates installer packages to be used in the RS Installer
inputs:
  branch-name-short:
    description: The branch name to publish the installer package for. This is the only the last part of branch name. Single word as develop, master or rc-17.11
    required: false
    default: null  
  builder-type:
    description: single, multiple or singleflat. Single = Creates single installer package based on source files or source directory. Multiple = Creates multiple installer packaages, one for each directory inside the source directory specified. singleflat = Creates a single installer package and flattens directories to root directory.
    required: true
    default: null
  output-dir:
    description: Directory to store the installer package.
    required: true
    default: null
  package-name:
    description: Name of the installer package to create. Needs to be the same as what is used in installer. Package name should be without extensions.
    required: false
    default: null
  package-version:
      description: Package version suffix apended to the package name before .pkg.zip.
      required: true
  publish-package:
    description: If set to true - publish the installer package.
    required: false
    default: false
  publish-root-url:
      description: The root url to where to publish the installer package. The url must end with backslash.
      required: false
  source-filePaths:
    description: Path to source files to include in the installer package.
    required: false
    default: null
  source-paths:
    description: Path to source directories to include in the installer package.
    required: false
    default: null
  search-filter:
    description: The search filter that applies for all source-paths. This can be multiple criteria, eg. *.dll;*.exe.
    required: false
    default: "*"
  tool-version:
    description: Version string for the version of RS Installer Package builder to use.
    required: true
    default: null
  working-dir:
    description: Working directory is used as base path for SourcePaths and SourceFilePaths.
    required: true
    default: null
runs:
  using: node12
  main: dist/index.js
